Updated tasks and environment file

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -2,10 +2,54 @@ version: '3'
 
 tasks:
 
-  setup-env:
-    desc: Create a micromamba environment for pixelatorR
+  install-pixelator-r:
+      desc: Install the PixelatorR R package into a specific environment
+      summary: |-
+        Install PixelatorR into an environment.
+
+        Variables:
+          DEPS: Whether to install pixelatorR dependencies. Default is false.
+
+        Example:
+        task install-pixelator-r ENV_NAME=my_env
+
+      vars:
+        DEPS: '{{ .DEPS | default "false" }}'
+      cmds:
+        - |
+          set -euo pipefail
+
+          # Determine the environment to use, handle unbound variable
+          ENV_TO_USE="{{.ENV_NAME}}"
+          if [ -z "$ENV_TO_USE" ]; then
+            ENV_TO_USE=$(basename $CONDA_DEFAULT_ENV)
+          fi
+
+          # Check if the environment exists, otherwise quit
+          micromamba env list | grep -q "$ENV_TO_USE" || {
+            echo "Environment $ENV_TO_USE does not exist. Please create it first."
+            exit 1
+          }
+
+          echo "Installing pixelatorR in environment $ENV_TO_USE"
+
+          micromamba run -n $ENV_TO_USE Rscript -e '
+            local({r <- getOption("repos")
+              r["CRAN"] <- "https://cran.r-project.org"
+              options(repos=r)
+            })
+            remotes::install_github(
+              "PixelgenTechnologies/pixelatorR",
+              upgrade="never",
+              deps={{ .DEPS | upper }}
+            )
+          '
+      silent: true
+
+  setup-env-bare:
+    desc: Create a micromamba environment with R installed
     summary: |-
-      Create a micromamba environment for pixelatorR
+      Create a micromamba environment with R installed
       --------------------------------------------------------------
 
       The environment name can be set using the ENV_NAME environment variable.
@@ -36,7 +80,45 @@ tasks:
       ENV_NAME: '{{.ENV_NAME | default "r-pixelator"}}'
     silent: true
 
-  install:
+  setup-env-pixelatorR:
+    desc: Create a micromamba environment with pixelatorR
+    summary: |-
+      Create a micromamba environment with pixelatorR
+      --------------------------------------------------------------
+
+      The environment name can be set using the ENV_NAME environment variable.
+
+      Examples:
+      task setup-env-pixelatorR ENV_NAME=my_env
+      task setup-env-pixelatorR ENV_NAME=my_env MICROMAMBA_ARGS="--platform osx-64"
+
+    vars:
+      MICROMAMBA_ARGS: '{{ .MICROMAMBA_ARGS | default "" }}'
+      ENV_NAME: '{{.ENV_NAME | default "r-pixelator"}}'
+
+    cmds:
+      - |
+        set -euo pipefail
+
+        # Check if micromamba is installed
+        if ! command -v micromamba &> /dev/null; then
+          echo "micromamba is not installed. Please install it first."
+          exit 1
+        fi
+
+        echo "Creating environment '{{.ENV_NAME}}'."
+
+        # Create the environment
+        if micromamba env create -y -n {{.ENV_NAME}} -f environment.yml {{ .MICROMAMBA_ARGS }}; then
+          echo "Environment '{{.ENV_NAME}}' created successfully."
+        else
+          echo "Failed to create environment '{{.ENV_NAME}}'."
+          exit 1
+        fi
+
+    silent: true
+
+  install-with-pak:
     desc: Install package dependencies
     summary: |-
       Install package dependencies
@@ -46,7 +128,7 @@ tasks:
       environment to use.
 
       Example:
-      task install ENV_NAME=my_env
+      task install-with-pak ENV_NAME=my_env
     cmds:
       - |
         set -euo pipefail
@@ -97,7 +179,7 @@ tasks:
           echo "Environment '$ENV_TO_USE' does not exist"
           exit 1
         else
-          echo "Using environment '$ENV_TO_USE'."
+          echo "Using environment '$ENV_TO_USE'"
           micromamba run -n $ENV_TO_USE bash -c '
             Rscript -e "devtools::document()"
           '
@@ -130,7 +212,7 @@ tasks:
           echo "Environment '$ENV_TO_USE' does not exist"
           exit 1
         else
-          echo "Using environment '$ENV_TO_USE'."
+          echo "Using environment '$ENV_TO_USE'"
           micromamba run -n $ENV_TO_USE bash -c '
             Rscript inst/dev/style-staged.R
           '
@@ -158,13 +240,15 @@ tasks:
           ENV_TO_USE=$(basename $CONDA_DEFAULT_ENV)
         fi
 
+        echo $ENV_TO_USE
+
         # Check if the environment exists
         if ! micromamba env list | grep -q "$ENV_TO_USE"; then
           echo "Environment '$ENV_TO_USE' does not exist"
           exit 1
         else
-          echo "Using environment '$ENV_TO_USE'."
-          micromamba run -n {{.ENV_NAME}} bash -c '
+          echo "Using environment '$ENV_TO_USE'"
+          micromamba run -n $ENV_TO_USE bash -c '
             Rscript inst/dev/test-staged.R
           '
         fi
@@ -192,11 +276,11 @@ tasks:
         fi
 
         # Check if the environment exists
-        if ! micromamba env list | grep -q "{{.ENV_NAME}}"; then
+        if ! micromamba env list | grep -q "$ENV_TO_USE"; then
           echo "Environment '$ENV_TO_USE' does not exist"
           exit 1
         else
-          echo "Using environment '$ENV_TO_USE'."
+          echo "Using environment '$ENV_TO_USE'"
           micromamba run -n $ENV_TO_USE bash -c '
             Rscript -e "devtools::test()"
           '
@@ -231,7 +315,7 @@ tasks:
           echo "Environment '$ENV_TO_USE' does not exist"
           exit 1
         else
-          echo "Using environment '$ENV_TO_USE'."
+          echo "Using environment '$ENV_TO_USE'"
           micromamba run -n $ENV_TO_USE bash -c '
             Rscript -e "devtools::run_examples()"
           '
